import { StyleSheet } from "react-native";
import { s, vs, ms, hp } from "../../../utils/responsive";

export const loginStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F5F5F0" },
  header: {
    flex: 0.7,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: vs(40),
    zIndex: 2,
  },
  title: { fontSize: ms(42), fontWeight: "bold", color: "#000" },
  subtitle: { fontSize: ms(20), color: "#000" },
  backgroundImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    width: "100%",
    height: hp(65),
    resizeMode: "cover",
    zIndex: 1,
  },
  loginCard: {
    flex: 0.8,
    backgroundColor: "rgba(245, 239, 218, 0.98)",
    marginHorizontal: s(40),
    marginBottom: vs(50),
    borderRadius: s(40),
    padding: s(20),
    justifyContent: "center",
    elevation: 10,
    zIndex: 3,
  },
  inputGroup: { marginBottom: vs(15) },
  label: { fontSize: ms(14), color: "#555", marginBottom: vs(2) },
  input: {
    borderBottomWidth: 1,
    borderBottomColor: "#000",
    fontSize: ms(15),
    paddingVertical: vs(6),
    minHeight: vs(40),
    color: "#000",
  },
  passwordInput: {
    flex: 1,
  },
  passwordContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  eyeButton: { paddingHorizontal: s(10) },
  eyeText: { fontSize: ms(18) },
  loginButton: {
    backgroundColor: "#7CEDA3",
    paddingVertical: vs(10),
    borderRadius: s(20),
    alignItems: "center",
    marginTop: vs(15),
  },
  buttonText: { fontSize: ms(16), fontWeight: "bold", color: "#333" },
  disabledButton: { backgroundColor: "#ccc" },
  forgotPasswordText: {
    fontSize: ms(12),
    color: "#555",
    textAlign: "center",
    marginTop: vs(10),
  },
  highlightedText: { color: "#ff0000", fontWeight: "bold" },
});
