import { StyleSheet } from "react-native";
import { s, vs, ms, hp } from "../../../../utils/responsive";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F2F2F2" },
  backButton: {
    position: "absolute",
    top: vs(50),
    left: s(20),
    zIndex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: s(20),
    width: s(40),
    height: s(40),
    justifyContent: "center",
    alignItems: "center",
  },
  backText: { color: "white", fontSize: ms(18) },
  titleText: {
    fontSize: ms(28),
    textAlign: "center",
    marginVertical: vs(18),
    fontFamily: "serif",
    marginTop: vs(60),
  },
  scrollContent: { alignItems: "center", paddingBottom: hp(14), paddingHorizontal: s(14) },
  promocionCard: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    borderRadius: s(15),
    width: "95%",
    minHeight: vs(120),
    alignItems: "center",
    marginBottom: vs(18),
    padding: s(14),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 5,
  },
  promocionImage: {
    width: s(100),
    height: s(100),
    borderRadius: s(50),
    marginRight: s(14),
    borderWidth: 2,
    borderColor: "#E6B5B5",
  },
  promocionInfo: { flex: 1, justifyContent: "center" },
  promocionName: { fontSize: ms(17), fontWeight: "bold", color: "#333", marginBottom: vs(6) },
  promocionType: { fontSize: ms(13), color: "#666", fontWeight: "600" },
  descuento: { fontSize: ms(17), fontWeight: "bold", color: "#dc3545", marginLeft: s(10) },
  bottomTab: {
    flexDirection: "row",
    backgroundColor: "#99D9C1",
    height: vs(65),
    position: "absolute",
    bottom: 0,
    width: "100%",
    justifyContent: "space-around",
    alignItems: "center",
  },
  tabItem: { alignItems: "center", justifyContent: "center" },
  tabLabel: { fontSize: ms(11), fontWeight: "bold", color: "#333", marginBottom: vs(4) },
  tabIconImg: { width: s(38), height: s(38), resizeMode: "contain" },
});
