import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F2F2F2" },
  titleText: {
    fontSize: 28,
    textAlign: "center",
    marginVertical: 16,
    fontFamily: "serif",
    color: "#333",
  },
  scrollContent: { alignItems: "center", paddingBottom: 100 },
  // Estado badge (socket)
  estadoBadge: {
    paddingVertical: 10,
    alignItems: "center",
    marginBottom: 4,
  },
  estadoText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 14,
    letterSpacing: 0.5,
  },
  // Location Box
  locationBox: {
    width: "95%",
    maxWidth: 340,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  locationTitle: {
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 8,
    color: "#000",
  },
  addressText: {
    fontSize: 15,
    color: "#333",
    marginBottom: 8,
    fontWeight: "600",
    textAlign: "center",
  },
  coords: {
    fontSize: 13,
    color: "#555",
    lineHeight: 20,
  },
  savedToggleBtn: {
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: "#F3F3F3",
    borderWidth: 1,
    borderColor: "#E0E0E0",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  savedToggleText: {
    color: "#333",
    fontSize: 13,
    fontWeight: "600",
  },
  savedToggleChevron: {
    color: "#555",
    fontSize: 12,
    fontWeight: "700",
  },
  usarUbicacionBtn: {
    marginTop: 12,
    paddingVertical: 11,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: "#2ECC71",
    alignItems: "center",
    justifyContent: "center",
  },
  usarUbicacionBtnText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  savedListBox: {
    marginTop: 8,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E6E6E6",
    backgroundColor: "#FAFAFA",
    paddingVertical: 6,
  },
  savedListState: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  savedListStateText: {
    marginTop: 6,
    color: "#666",
    fontSize: 12,
    textAlign: "center",
  },
  savedItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#ECECEC",
  },
  savedItemTextWrap: {
    flex: 1,
    paddingRight: 10,
  },
  savedItemUseBtn: {
    minWidth: 54,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#EAF6EE",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    paddingHorizontal: 10,
  },
  savedItemUseBtnActive: {
    backgroundColor: "#99D9C1",
  },
  savedItemUseText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#2E7D4F",
  },
  savedItemUseTextActive: {
    color: "#1F4D36",
  },
  savedItemTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#333",
  },
  savedItemSubtitle: {
    marginTop: 2,
    fontSize: 12,
    color: "#666",
  },
  savedItemSelectedBadge: {
    marginTop: 4,
    fontSize: 11,
    fontWeight: "700",
    color: "#1F4D36",
  },
  savedItemArrowBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#EAF6EE",
    alignItems: "center",
    justifyContent: "center",
  },
  savedItemArrow: {
    fontSize: 13,
    color: "#2E7D4F",
    fontWeight: "900",
    lineHeight: 13,
  },
  // Map Container
  mapContainer: {
    width: "95%",
    maxWidth: 420,
    height: 260,
    alignSelf: "center",
    borderRadius: 28,
    overflow: "hidden",
    backgroundColor: "#FFF",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
    zIndex: 2000,
    marginBottom: 100,
    position: "relative",
  },
  mapContainerExpanded: {
    width: "95%",
    maxWidth: 420,
    height: 500,
    alignSelf: "center",
    borderRadius: 28,
    marginBottom: 40,
    backgroundColor: "#FFF",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
    zIndex: 2000,
    position: "relative",
  },
  mapWebView: {
    width: "100%",
    height: "100%",
    border: "none",
  },
  mapBtn: {
    position: "absolute",
    top: 18,
    right: 18,
    zIndex: 3000,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 14,
  },
  mapBtnText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
    localizarBtn: {
      position: "absolute",
      top: 18,
      left: 18,
      zIndex: 3000,
      backgroundColor: "rgba(46, 204, 113, 0.9)",
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 12,
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 4,
    },
    localizarBtnText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "700",
    },
  instructions: {
    position: "absolute",
    bottom: 20,
    left: 20,
    zIndex: 3000,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    color: "#fff",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    fontSize: 13,
  },
  paseadorCard: {
    width: "95%",
    maxWidth: 420,
    backgroundColor: "#99D9C1",
    borderRadius: 14,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16,
  },
  paseadorFoto: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 2,
    borderColor: "#FFFFFF",
    backgroundColor: "#FFFFFF",
  },
  paseadorInfo: { flex: 1, marginLeft: 12 },
  paseadorNombre: { color: "#1F2A26", fontSize: 16, fontWeight: "700" },
  paseadorCalificacion: { color: "#2E5D4D", fontSize: 12, marginTop: 4, fontWeight: "600" },
  paseadorArrow: { color: "#1F4D36", fontSize: 30, fontWeight: "700", marginLeft: 8 },
  addButton: {
    backgroundColor: "#E6B5B5",
    width: 80,
    height: 38,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 14,
    marginBottom: 18,
  },
  addIcon: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#333",
    lineHeight: 30,
  },
  addButtonLabel: {
    marginTop: -10,
    marginBottom: 18,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: "rgba(230, 181, 181, 0.28)",
    color: "#7A4B4B",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    overflow: "hidden",
  },
  // Loading / Error
  loadingWrapper: {
    width: "100%",
    height: 360,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    marginTop: 14,
    fontSize: 14,
    color: "#555",
  },
  errorText: {
    marginTop: 16,
    color: "#D00",
    fontSize: 14,
    textAlign: "center",
    paddingHorizontal: 16,
  },
  canceladoModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  canceladoModalCard: {
    width: "100%",
    maxWidth: 340,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 22,
    alignItems: "center",
  },
  canceladoModalText: {
    color: "#222",
    fontSize: 17,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 18,
  },
  canceladoModalButton: {
    backgroundColor: "#2E7D4F",
    borderRadius: 10,
    paddingHorizontal: 26,
    paddingVertical: 10,
  },
  canceladoModalButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  entregaModalActions: {
    flexDirection: "row",
    gap: 10,
  },
  entregaModalNoButton: {
    backgroundColor: "#D45B5B",
    borderRadius: 10,
    paddingHorizontal: 26,
    paddingVertical: 10,
  },
  // Bottom tab (cliente — usa imágenes)
  bottomTab: {
    flexDirection: "row",
    backgroundColor: "#99D9C1",
    height: 70,
    position: "absolute",
    bottom: 0,
    width: "100%",
    justifyContent: "space-around",
    alignItems: "center",
  },
  tabItem: {
    alignItems: "center",
    justifyContent: "center",
  },
  tabIconImg: { width: 40, height: 40, resizeMode: "contain" },
  tabLabel: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 5,
  },
});
