import { StyleSheet } from "react-native";
import { s, vs, ms } from "../../utils/responsive";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F5F0",
  },
  content: {
    padding: s(16),
    paddingBottom: vs(100),
    paddingTop: vs(68),
  },
  topRightShortcut: {
    position: "absolute",
    top: vs(20),
    right: s(12),
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#73C6A6",
    borderRadius: s(16),
    paddingHorizontal: s(12),
    paddingVertical: vs(7),
    zIndex: 10,
  },
  topRightShortcutText: {
    color: "#0A7A4A",
    fontSize: ms(12),
    fontWeight: "700",
  },
  title: {
    fontSize: ms(22),
    fontWeight: "800",
    color: "#1F2937",
  },
  subtitle: {
    marginTop: vs(6),
    marginBottom: vs(14),
    color: "#4B5563",
    fontSize: ms(13),
  },
  greenCard: {
    backgroundColor: "#99D9C1",
    borderRadius: s(18),
    padding: s(14),
    borderWidth: 1,
    borderColor: "#73C6A6",
  },
  sectionTitle: {
    fontSize: ms(16),
    fontWeight: "800",
    color: "#114B36",
    marginBottom: vs(8),
  },
  optionRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: s(12),
    paddingVertical: vs(11),
    paddingHorizontal: s(12),
    marginBottom: vs(8),
    borderWidth: 1,
    borderColor: "#DDE3E1",
  },
  optionRowSelected: {
    borderColor: "#0A7A4A",
    backgroundColor: "#ECFDF3",
  },
  radio: {
    width: s(20),
    height: s(20),
    borderRadius: s(10),
    borderWidth: 2,
    borderColor: "#9CA3AF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: s(10),
  },
  radioSelected: {
    borderColor: "#0A7A4A",
  },
  radioDot: {
    width: s(10),
    height: s(10),
    borderRadius: s(5),
    backgroundColor: "#0A7A4A",
  },
  optionContent: {
    flex: 1,
  },
  optionLabel: {
    fontSize: ms(14),
    fontWeight: "700",
    color: "#111827",
  },
  optionSubtitle: {
    marginTop: vs(2),
    fontSize: ms(12),
    color: "#6B7280",
  },
  summaryBox: {
    marginTop: vs(8),
    backgroundColor: "#FFFFFF",
    borderRadius: s(14),
    padding: s(12),
    borderWidth: 1,
    borderColor: "#DDE3E1",
  },
  summaryTitle: {
    fontSize: ms(14),
    fontWeight: "800",
    color: "#1F2937",
    marginBottom: vs(8),
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: vs(6),
  },
  summaryLabel: {
    color: "#6B7280",
    fontSize: ms(13),
  },
  summaryValue: {
    color: "#1F2937",
    fontSize: ms(13),
    fontWeight: "600",
  },
  summaryDivider: {
    height: 1,
    backgroundColor: "#E5E7EB",
    marginVertical: vs(6),
  },
  totalLabel: {
    color: "#111827",
    fontSize: ms(15),
    fontWeight: "800",
  },
  totalValue: {
    color: "#0A7A4A",
    fontSize: ms(18),
    fontWeight: "900",
  },
  confirmBtn: {
    marginTop: vs(12),
    backgroundColor: "#0A7A4A",
    paddingVertical: vs(14),
    borderRadius: s(14),
    alignItems: "center",
  },
  confirmBtnText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: ms(16),
  },
  note: {
    marginTop: vs(10),
    color: "#14532D",
    fontSize: ms(12),
    textAlign: "center",
    lineHeight: ms(17),
  },
  bottomTab: {
    flexDirection: "row",
    backgroundColor: "#99D9C1",
    height: vs(65),
    position: "absolute",
    bottom: 0,
    width: "100%",
    justifyContent: "space-around",
    alignItems: "center",
  },
  tabItem: {
    alignItems: "center",
    justifyContent: "center",
  },
  tabIconImg: {
    width: s(38),
    height: s(38),
    resizeMode: "contain",
  },
  tabLabel: {
    fontSize: ms(11),
    fontWeight: "bold",
    color: "#333",
    marginBottom: vs(4),
  },
});
