import { StyleSheet } from "react-native";
import { s, vs, ms } from "../../utils/responsive";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F2F2F2" },
  content: { padding: s(18), paddingTop: vs(50), paddingBottom: vs(95) },
  backButton: {
    alignSelf: "flex-start",
    backgroundColor: "#99D9C1",
    borderRadius: s(18),
    paddingHorizontal: s(14),
    paddingVertical: vs(8),
  },
  backText: { color: "#1F4D36", fontSize: ms(14), fontWeight: "700" },
  title: { fontSize: ms(25), color: "#333", fontFamily: "serif", textAlign: "center", marginVertical: vs(18) },
  card: {
    backgroundColor: "#99D9C1",
    borderRadius: s(18),
    padding: s(20),
    alignItems: "center",
  },
  photo: {
    width: s(120),
    height: s(120),
    borderRadius: s(60),
    borderWidth: 3,
    borderColor: "#FFFFFF",
    backgroundColor: "#FFFFFF",
  },
  name: { color: "#1F2A26", fontSize: ms(22), fontWeight: "700", marginTop: vs(14), textAlign: "center" },
  averageRating: { alignItems: "center", marginTop: vs(7) },
  averageStars: { color: "#F4B942", fontSize: ms(25), fontWeight: "700", letterSpacing: 0 },
  averageScore: { color: "#1F4D36", fontSize: ms(16), fontWeight: "800", marginTop: vs(2) },
  detailGroup: { width: "100%", marginTop: vs(18) },
  label: { color: "#1F4D36", fontSize: ms(14), fontWeight: "700", marginBottom: vs(5) },
  value: { backgroundColor: "rgba(255,255,255,0.8)", borderRadius: s(10), color: "#333", fontSize: ms(14), padding: s(12) },
  reviewCard: { backgroundColor: "rgba(255,255,255,0.82)", borderRadius: s(10), padding: s(12), marginBottom: vs(8) },
  reviewHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  reviewClient: { color: "#1F2A26", fontSize: ms(13), fontWeight: "800", flex: 1 },
  reviewStars: { color: "#F4B942", fontSize: ms(15) },
  reviewScore: { color: "#527064", fontSize: ms(11), fontWeight: "700", marginTop: vs(3) },
  reviewComment: { color: "#444", fontSize: ms(12), lineHeight: vs(17), marginTop: vs(7) },
  bottomTab: {
    flexDirection: "row",
    backgroundColor: "#99D9C1",
    height: vs(70),
    position: "absolute",
    bottom: 0,
    width: "100%",
    justifyContent: "space-around",
    alignItems: "center",
  },
  tabItem: { alignItems: "center", justifyContent: "center" },
  tabIconImg: { width: s(40), height: s(40), resizeMode: "contain" },
  tabLabel: { fontSize: ms(11), fontWeight: "bold", color: "#333", marginBottom: vs(4) },
});
