import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F2F2F2" },
  titleText: {
    fontSize: 28,
    textAlign: "center",
    marginVertical: 16,
    fontFamily: "serif",
    color: "#333",
  },
  scrollContent: { alignItems: "center", paddingBottom: 100 },
  // Estado badge (socket)
  estadoBadge: {
    paddingVertical: 10,
    alignItems: "center",
    marginBottom: 4,
  },
  estadoText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 14,
    letterSpacing: 0.5,
  },
  // Location Box
  locationBox: {
    width: "95%",
    maxWidth: 340,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  locationTitle: {
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 8,
    color: "#000",
  },
  addressText: {
    fontSize: 15,
    color: "#333",
    marginBottom: 8,
    fontWeight: "600",
    textAlign: "center",
  },
  coords: {
    fontSize: 13,
    color: "#555",
    lineHeight: 20,
  },
  // Map Container
  mapContainer: {
    width: "95%",
    maxWidth: 420,
    height: 260,
    alignSelf: "center",
    borderRadius: 28,
    overflow: "hidden",
    backgroundColor: "#FFF",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
    zIndex: 2000,
    marginBottom: 100,
    position: "relative",
  },
  mapContainerExpanded: {
    width: "95%",
    maxWidth: 420,
    height: 500,
    alignSelf: "center",
    borderRadius: 28,
    marginBottom: 40,
    backgroundColor: "#FFF",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
    zIndex: 2000,
    position: "relative",
  },
  mapWebView: {
    width: "100%",
    height: "100%",
    border: "none",
  },
  mapBtn: {
    position: "absolute",
    top: 18,
    right: 18,
    zIndex: 3000,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 14,
  },
  mapBtnText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  instructions: {
    position: "absolute",
    bottom: 20,
    left: 20,
    zIndex: 3000,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    color: "#fff",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    fontSize: 13,
  },
  // Loading / Error
  loadingWrapper: {
    width: "100%",
    height: 360,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    marginTop: 14,
    fontSize: 14,
    color: "#555",
  },
  errorText: {
    marginTop: 16,
    color: "#D00",
    fontSize: 14,
    textAlign: "center",
    paddingHorizontal: 16,
  },
  // Bottom tab (cliente — usa imágenes)
  bottomTab: {
    flexDirection: "row",
    backgroundColor: "#99D9C1",
    height: 70,
    position: "absolute",
    bottom: 0,
    width: "100%",
    justifyContent: "space-around",
    alignItems: "center",
  },
  tabItem: {
    alignItems: "center",
    justifyContent: "center",
  },
  tabIconImg: { width: 40, height: 40, resizeMode: "contain" },
  tabLabel: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 5,
  },
});
