import { StyleSheet } from "react-native";
import { s, vs, ms, hp } from "../../../utils/responsive";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F2F2F2",
    paddingBottom: vs(8),
  },
  navbar: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: s(18),
    paddingTop: vs(50),
  },
  navIcon: { fontSize: ms(26) },
  titleText: {
    fontSize: ms(28),
    textAlign: "center",
    marginVertical: vs(18),
    fontFamily: "serif",
  },
  scrollContent: {
    alignItems: "center",
    paddingBottom: hp(32),
    paddingHorizontal: s(16),
    paddingTop: vs(6),
  },
  petCard: {
    flexDirection: "row",
    backgroundColor: "#D9D9D9",
    borderRadius: s(24),
    width: "100%",
    minHeight: vs(92),
    alignItems: "center",
    marginBottom: vs(18),
    padding: s(10),
    overflow: "hidden",
  },
  petImage: {
    width: s(74),
    height: s(74),
    borderRadius: s(37),
    borderWidth: 1,
    borderColor: "#BFA6A6",
  },
  petInfo: {
    flex: 1,
    marginLeft: s(14),
    justifyContent: "center",
    flexShrink: 1,
  },
  petName: { fontSize: ms(18), fontWeight: "bold", marginBottom: vs(2) },
  petDetails: { fontSize: ms(13), color: "#444", flexShrink: 1 },
  searchCircle: {
    backgroundColor: "#E6B5B5",
    width: s(140),
    height: s(140),
    borderRadius: s(70),
    justifyContent: "center",
    alignItems: "center",
    marginTop: vs(18),
  },
  searchText: { textAlign: "center", fontWeight: "bold", fontSize: ms(13) },
  addButton: {
    backgroundColor: "#E6B5B5",
    width: s(80),
    height: vs(38),
    borderRadius: s(20),
    justifyContent: "center",
    alignItems: "center",
    marginTop: vs(18),
  },
  addIcon: { fontSize: ms(28), fontWeight: "bold" },
  addHintText: {
    marginTop: vs(8),
    color: "#666",
    fontSize: ms(12),
    fontWeight: "300",
    letterSpacing: 0.2,
    marginBottom: vs(8),
  },
  paseadorCard: {
    width: "88%",
    backgroundColor: "#FFFFFF",
    borderRadius: s(16),
    padding: s(12),
    marginTop: vs(12),
    marginBottom: vs(20),
    borderWidth: 1,
    borderColor: "#E7E7E7",
  },
  paseadorCardSelected: {
    borderColor: "#80C6AE",
    shadowColor: "#2B6452",
    shadowOpacity: 0.16,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  paseadorCardTitle: {
    fontSize: ms(14),
    fontWeight: "700",
    color: "#333",
    marginBottom: vs(10),
  },
  paseadorContentRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  paseadorLoadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: s(10),
  },
  paseadorPhoto: {
    width: s(62),
    height: s(62),
    borderRadius: s(31),
    borderWidth: 1,
    borderColor: "#D2D2D2",
    backgroundColor: "#F5F5F5",
  },
  paseadorTextWrap: {
    flex: 1,
    marginLeft: s(12),
  },
  paseadorNombre: {
    fontSize: ms(15),
    fontWeight: "700",
    color: "#1F2A26",
    marginBottom: vs(4),
  },
  paseadorDescripcion: {
    fontSize: ms(12),
    color: "#4D4D4D",
    lineHeight: ms(16),
  },
  paseadorEstado: {
    marginTop: vs(6),
    fontSize: ms(11),
    color: "#4A7D6E",
    fontWeight: "600",
  },
  paseadorTapHint: {
    marginTop: vs(6),
    fontSize: ms(11),
    color: "#3C6C5E",
    fontWeight: "600",
  },
  paseadorEmptyText: {
    fontSize: ms(12),
    color: "#666",
  },
  entregaCard: {
    width: "88%",
    backgroundColor: "#99D9C1",
    borderRadius: s(16),
    padding: s(14),
    marginTop: vs(12),
    alignItems: "center",
  },
  entregaTitle: { color: "#1F2A26", fontSize: ms(14), fontWeight: "700", textAlign: "center" },
  entregaActions: { flexDirection: "row", gap: s(12), marginTop: vs(12) },
  entregaYesButton: {
    backgroundColor: "#2E7D4F",
    borderRadius: s(18),
    paddingHorizontal: s(18),
    paddingVertical: vs(8),
    marginTop: vs(12),
  },
  entregaNoButton: {
    backgroundColor: "#D45B5B",
    borderRadius: s(18),
    paddingHorizontal: s(18),
    paddingVertical: vs(8),
    marginTop: vs(12),
  },
  entregaButtonText: { color: "#FFFFFF", fontSize: ms(13), fontWeight: "700" },
  entregaTimer: { color: "#1F4D36", fontSize: ms(26), fontWeight: "800", marginTop: vs(10) },
  entregaTimerUrgent: { color: "#C62828" },
  busquedaCard: {
    width: "88%",
    backgroundColor: "#99D9C1",
    borderRadius: s(16),
    padding: s(14),
    marginTop: vs(12),
    alignItems: "center",
  },
  busquedaTitle: { color: "#1F2A26", fontSize: ms(15), fontWeight: "700", textAlign: "center" },
  busquedaTimer: { color: "#2E7D4F", fontSize: ms(28), fontWeight: "800", marginTop: vs(10) },
  btnCancelarBusqueda: {
    backgroundColor: "#E74C3C",
    borderRadius: s(18),
    paddingHorizontal: s(20),
    paddingVertical: vs(10),
    marginTop: vs(12),
  },
  btnCancelarText: { color: "#FFFFFF", fontSize: ms(13), fontWeight: "700" },
  canceladoModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: s(24),
  },
  canceladoModalCard: {
    width: "100%",
    maxWidth: s(340),
    backgroundColor: "#FFFFFF",
    borderRadius: s(16),
    padding: s(22),
    alignItems: "center",
  },
  canceladoModalText: {
    color: "#222",
    fontSize: ms(17),
    fontWeight: "700",
    textAlign: "center",
    marginBottom: vs(18),
  },
  canceladoModalButton: {
    backgroundColor: "#2E7D4F",
    borderRadius: s(10),
    paddingHorizontal: s(26),
    paddingVertical: vs(10),
  },
  entregaModalNoButton: {
    backgroundColor: "#D45B5B",
    borderRadius: 10,
    paddingHorizontal: 26,
    paddingVertical: 10,
  },
  canceladoModalButtonText: { color: "#FFFFFF", fontSize: ms(14), fontWeight: "700" },
  bottomTab: {
    flexDirection: "row",
    backgroundColor: "#99D9C1",
    height: vs(84),
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    justifyContent: "space-around",
    alignItems: "center",
    paddingBottom: vs(10),
    paddingTop: vs(6),
    zIndex: 20,
    borderTopWidth: 1,
    borderTopColor: "#7FB9A3",
    elevation: 12,
    shadowColor: "#000",
    shadowOpacity: 0.16,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: -2 },
  },
  tabIconImg: { width: s(38), height: s(38), resizeMode: "contain" },
  tabItem: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: s(10),
    minWidth: s(60),
  },
  tabLabel: { fontSize: ms(11), fontWeight: "bold", color: "#333", marginBottom: vs(4) },
});
