import { StyleSheet } from "react-native";
import { s, vs, ms, hp } from "../../../utils/responsive";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F2F2F2" },
  navbar: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: s(18),
    paddingTop: vs(50),
  },
  navIcon: { fontSize: ms(26) },
  titleText: {
    fontSize: ms(28),
    textAlign: "center",
    marginVertical: vs(18),
    fontFamily: "serif",
  },
  scrollContent: { alignItems: "center", paddingBottom: hp(14) },
  petCard: {
    flexDirection: "row",
    backgroundColor: "#D9D9D9",
    borderRadius: s(50),
    width: "88%",
    height: vs(90),
    alignItems: "center",
    marginBottom: vs(18),
    padding: s(10),
  },
  petImage: { width: s(70), height: s(70), borderRadius: s(35), borderWidth: 1 },
  petInfo: { marginLeft: s(14) },
  petName: { fontSize: ms(18), fontWeight: "bold" },
  searchCircle: {
    backgroundColor: "#E6B5B5",
    width: s(140),
    height: s(140),
    borderRadius: s(70),
    justifyContent: "center",
    alignItems: "center",
    marginTop: vs(18),
  },
  searchText: { textAlign: "center", fontWeight: "bold", fontSize: ms(13) },
  addButton: {
    backgroundColor: "#E6B5B5",
    width: s(80),
    height: vs(38),
    borderRadius: s(20),
    justifyContent: "center",
    alignItems: "center",
    marginTop: vs(18),
  },
  addIcon: { fontSize: ms(28), fontWeight: "bold" },
  historialBtn: {
    backgroundColor: "#EDF9F4",
    borderWidth: 1,
    borderColor: "#99D9C1",
    borderRadius: s(20),
    paddingHorizontal: s(28),
    paddingVertical: vs(10),
    marginTop: vs(14),
  },
  historialText: { fontSize: ms(14), fontWeight: "bold", color: "#22a06b" },
  petDetails: { fontSize: ms(13), color: "#555" },
  bottomTab: {
    flexDirection: "row",
    backgroundColor: "#99D9C1",
    height: vs(65),
    position: "absolute",
    bottom: 0,
    width: "100%",
    justifyContent: "space-around",
    alignItems: "center",
  },
  tabIconImg: { width: s(38), height: s(38), resizeMode: "contain" },
  tabItem: { alignItems: "center", justifyContent: "center" },
  tabLabel: { fontSize: ms(11), fontWeight: "bold", color: "#333", marginBottom: vs(4) },
});
