import { StyleSheet } from "react-native";
import { s, vs, ms, hp } from "../../../utils/responsive";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F2F2F2" },
  navbar: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: s(18),
    paddingTop: vs(50),
  },
  navIcon: { fontSize: ms(26) },
  titleText: {
    fontSize: ms(28),
    textAlign: "center",
    marginVertical: vs(18),
    fontFamily: "serif",
  },
  scrollContent: { alignItems: "center", paddingBottom: hp(14) },
  petCard: {
    flexDirection: "row",
    backgroundColor: "#D9D9D9",
    borderRadius: s(50),
    width: "88%",
    height: vs(90),
    alignItems: "center",
    marginBottom: vs(18),
    padding: s(10),
  },
  petImage: { width: s(70), height: s(70), borderRadius: s(35), borderWidth: 1 },
  petInfo: { marginLeft: s(14) },
  petName: { fontSize: ms(18), fontWeight: "bold" },
  searchCircle: {
    backgroundColor: "#E6B5B5",
    width: s(140),
    height: s(140),
    borderRadius: s(70),
    justifyContent: "center",
    alignItems: "center",
    marginTop: vs(18),
  },
  searchText: { textAlign: "center", fontWeight: "bold", fontSize: ms(13) },
  addButton: {
    backgroundColor: "#E6B5B5",
    width: s(80),
    height: vs(38),
    borderRadius: s(20),
    justifyContent: "center",
    alignItems: "center",
    marginTop: vs(18),
  },
  addIcon: { fontSize: ms(28), fontWeight: "bold" },
  addHintText: {
    marginTop: vs(8),
    color: "#666",
    fontSize: ms(12),
    fontWeight: "300",
    letterSpacing: 0.2,
    marginBottom: vs(8),
  },
  paseadorCard: {
    width: "88%",
    backgroundColor: "#FFFFFF",
    borderRadius: s(16),
    padding: s(12),
    marginTop: vs(12),
    marginBottom: vs(20),
    borderWidth: 1,
    borderColor: "#E7E7E7",
  },
  paseadorCardTitle: {
    fontSize: ms(14),
    fontWeight: "700",
    color: "#333",
    marginBottom: vs(10),
  },
  paseadorContentRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  paseadorLoadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: s(10),
  },
  paseadorPhoto: {
    width: s(62),
    height: s(62),
    borderRadius: s(31),
    borderWidth: 1,
    borderColor: "#D2D2D2",
    backgroundColor: "#F5F5F5",
  },
  paseadorTextWrap: {
    flex: 1,
    marginLeft: s(12),
  },
  paseadorNombre: {
    fontSize: ms(15),
    fontWeight: "700",
    color: "#1F2A26",
    marginBottom: vs(4),
  },
  paseadorDescripcion: {
    fontSize: ms(12),
    color: "#4D4D4D",
    lineHeight: ms(16),
  },
  paseadorEstado: {
    marginTop: vs(6),
    fontSize: ms(11),
    color: "#4A7D6E",
    fontWeight: "600",
  },
  paseadorEmptyText: {
    fontSize: ms(12),
    color: "#666",
  },
  bottomTab: {
    flexDirection: "row",
    backgroundColor: "#99D9C1",
    height: vs(65),
    position: "absolute",
    bottom: 0,
    width: "100%",
    justifyContent: "space-around",
    alignItems: "center",
  },
  tabIconImg: { width: s(38), height: s(38), resizeMode: "contain" },
  tabItem: { alignItems: "center", justifyContent: "center" },
  tabLabel: { fontSize: ms(11), fontWeight: "bold", color: "#333", marginBottom: vs(4) },
});
