import { StyleSheet } from "react-native";
import { s, vs, ms, hp } from "../../../utils/responsive";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f5f5f5" },
  backButton: {
    position: "absolute",
    top: vs(50),
    left: s(20),
    zIndex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: s(20),
    width: s(40),
    height: s(40),
    justifyContent: "center",
    alignItems: "center",
  },
  backText: { color: "white", fontSize: ms(18) },
  scrollContent: {
    alignItems: "center",
    paddingTop: vs(100),
    paddingHorizontal: s(20),
    paddingBottom: vs(95),
  },
  petImage: {
    width: s(180),
    height: s(180),
    borderRadius: s(90),
    marginBottom: vs(18),
  },
  petName: { fontSize: ms(29), fontWeight: "bold", color: "#333", marginBottom: vs(18) },
  detailsContainer: {
    width: "100%",
    backgroundColor: "#99D9C1",
    borderRadius: s(10),
    padding: s(18),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  detailsTitle: {
    fontSize: ms(20),
    fontWeight: "bold",
    color: "#333",
    marginBottom: vs(8),
  },
  detailRow: {
    marginTop: vs(8),
  },
  detailLabel: { fontSize: ms(15), fontWeight: "bold", color: "#4a3b2f" },
  detailValue: { fontSize: ms(16), color: "#333", marginBottom: vs(2), lineHeight: ms(24) },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: vs(18),
  },
  editButton: {
    backgroundColor: "#007bff",
    paddingVertical: vs(12),
    paddingHorizontal: s(16),
    borderRadius: s(8),
    flex: 1,
    marginRight: s(10),
  },
  deleteButton: {
    backgroundColor: "#dc3545",
    paddingVertical: vs(12),
    paddingHorizontal: s(16),
    borderRadius: s(8),
    flex: 1,
    marginLeft: s(10),
  },
  buttonText: { color: "white", fontSize: ms(16), fontWeight: "bold", textAlign: "center" },
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    backgroundColor: "white",
    borderRadius: s(10),
    padding: s(20),
    width: "80%",
    maxWidth: s(300),
    alignItems: "center",
    elevation: 5,
  },
  modalTitle: { fontSize: ms(18), fontWeight: "bold", color: "#333", marginBottom: vs(8) },
  modalMessage: { fontSize: ms(15), color: "#555", textAlign: "center", marginBottom: vs(18) },
  modalButtons: { flexDirection: "row", justifyContent: "space-between", width: "100%" },
  cancelButton: {
    backgroundColor: "#6c757d",
    paddingVertical: vs(11),
    paddingHorizontal: s(16),
    borderRadius: s(8),
    flex: 1,
    marginRight: s(10),
  },
  confirmButton: {
    backgroundColor: "#dc3545",
    paddingVertical: vs(11),
    paddingHorizontal: s(16),
    borderRadius: s(8),
    flex: 1,
    marginLeft: s(10),
  },
  bottomTab: {
    flexDirection: "row",
    backgroundColor: "#99D9C1",
    height: vs(65),
    position: "absolute",
    bottom: 0,
    width: "100%",
    justifyContent: "space-around",
    alignItems: "center",
  },
  tabIconImg: { width: s(38), height: s(38), resizeMode: "contain" },
  tabItem: { alignItems: "center", justifyContent: "center" },
  tabLabel: { fontSize: ms(11), fontWeight: "bold", color: "#333", marginBottom: vs(4) },
});
