import { StyleSheet } from "react-native";
import { s, vs, ms } from "../../../utils/responsive";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f5f5f5" },
  backButton: {
    position: "absolute",
    top: vs(50),
    left: s(20),
    zIndex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: s(20),
    width: s(40),
    height: s(40),
    justifyContent: "center",
    alignItems: "center",
  },
  backText: { color: "white", fontSize: ms(18) },
  scrollContent: {
    alignItems: "center",
    paddingTop: vs(100),
    paddingHorizontal: s(20),
    paddingBottom: vs(30),
  },
  ofertaImage: {
    width: s(180),
    height: s(180),
    borderRadius: s(15),
    marginBottom: vs(18),
    borderWidth: 3,
    borderColor: "#dc3545",
  },
  ofertaName: { fontSize: ms(26), fontWeight: "bold", color: "#333", marginBottom: vs(10) },
  flashBadge: {
    backgroundColor: "#dc3545",
    paddingVertical: vs(9),
    paddingHorizontal: s(18),
    borderRadius: s(8),
    marginBottom: vs(14),
    borderWidth: 2,
    borderColor: "#fff",
    elevation: 5,
  },
  flashText: { color: "white", fontSize: ms(18), fontWeight: "bold", textAlign: "center" },
  priceContainer: { marginBottom: vs(18), alignItems: "center" },
  precioOriginal: { fontSize: ms(17), color: "#999", textDecorationLine: "line-through", marginBottom: vs(4) },
  precio: { fontSize: ms(36), fontWeight: "bold", color: "#28a745" },
  detailsContainer: {
    width: "100%",
    backgroundColor: "white",
    borderRadius: s(10),
    padding: s(18),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: vs(18),
  },
  detailLabel: { fontSize: ms(15), fontWeight: "bold", color: "#555", marginTop: vs(10) },
  detailValue: { fontSize: ms(15), color: "#333", marginBottom: vs(4), lineHeight: ms(22) },
  stockValue: { fontSize: ms(15), fontWeight: "bold", color: "#28a745", marginBottom: vs(4) },
  tiempoValue: { fontSize: ms(15), fontWeight: "bold", color: "#dc3545", marginBottom: vs(4) },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: vs(18),
  },
  comprarButton: {
    backgroundColor: "#dc3545",
    paddingVertical: vs(12),
    paddingHorizontal: s(16),
    borderRadius: s(8),
    flex: 1,
    marginRight: s(10),
  },
  compartirButton: {
    backgroundColor: "#17a2b8",
    paddingVertical: vs(12),
    paddingHorizontal: s(16),
    borderRadius: s(8),
    flex: 1,
    marginLeft: s(10),
  },
  buttonText: { color: "white", fontSize: ms(15), fontWeight: "bold", textAlign: "center" },
});
