import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F2F2F2" },
  titleText: {
    fontSize: 28,
    textAlign: "center",
    marginVertical: 16,
    fontFamily: "serif",
    color: "#333",
  },
  scrollContent: { alignItems: "center", paddingBottom: 100 },
  // Location Box
  locationBox: {
    width: "95%",
    maxWidth: 340,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  locationTitle: {
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 8,
    color: "#000",
  },
  addressText: {
    fontSize: 15,
    color: "#333",
    marginBottom: 8,
    fontWeight: "600",
    textAlign: "center",
  },
  coords: {
    fontSize: 13,
    color: "#555",
    lineHeight: 20,
  },
  // Map Container
  mapContainer: {
    width: "95%",
    maxWidth: 420,
    height: 260,
    alignSelf: "center",
    borderRadius: 28,
    overflow: "hidden",
    backgroundColor: "#FFF",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
    zIndex: 2000,
    marginBottom: 100,
    position: "relative",
  },
  mapContainerExpanded: {
    width: "95%",
    maxWidth: 420,
    height: 500,
    alignSelf: "center",
    borderRadius: 28,
    marginBottom: 40,
    backgroundColor: "#FFF",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
    zIndex: 2000,
    position: "relative",
  },
  mapWebView: {
    width: "100%",
    height: "100%",
    border: "none",
  },
  activeMapBannerTop: {
    width: "95%",
    alignSelf: "center",
    marginBottom: 12,
    backgroundColor: "rgba(34, 197, 94, 0.95)",
    borderRadius: 18,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  activeBannerTitle: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 4,
  },
  activeBannerTime: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "800",
  },
  activeBannerButton: {
    backgroundColor: "#064e3b",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 14,
  },
  activeBannerButtonDisabled: {
    opacity: 0.6,
  },
  activeBannerButtonText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "700",
  },
  mapBtn: {
    position: "absolute",
    top: 18,
    right: 18,
    zIndex: 3000,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 14,
  },
  mapBtnText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  instructions: {
    position: "absolute",
    bottom: 20,
    left: 20,
    zIndex: 3000,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    color: "#fff",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    fontSize: 13,
  },
  // Loading / Error
  loadingWrapper: {
    width: "100%",
    height: 360,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    marginTop: 14,
    fontSize: 14,
    color: "#555",
  },
  errorText: {
    marginTop: 16,
    color: "#D00",
    fontSize: 14,
    textAlign: "center",
    paddingHorizontal: 16,
  },
  // Bottom tab (paseador — 4 tabs)
  bottomTab: {
    flexDirection: "row",
    backgroundColor: "#99D9C1",
    height: 65,
    justifyContent: "space-around",
    alignItems: "center",
  },
  tabItem: {
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  tabIcon: {
    fontSize: 20,
  },
  tabLabel: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#1A1A1A",
  },
});
