import { StyleSheet } from "react-native";
import { s, vs, ms } from "../../../utils/responsive";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f5f5f5" },
  backButton: {
    position: "absolute",
    top: vs(50),
    left: s(20),
    zIndex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: s(20),
    width: s(40),
    height: s(40),
    justifyContent: "center",
    alignItems: "center",
  },
  backText: { color: "white", fontSize: ms(18) },
  scrollContent: {
    alignItems: "center",
    paddingTop: vs(100),
    paddingHorizontal: s(20),
    paddingBottom: vs(30),
  },
  paseadorImage: {
    width: s(180),
    height: s(180),
    borderRadius: s(90),
    marginBottom: vs(18),
    borderWidth: 3,
    borderColor: "#99D9C1",
  },
  paseadorName: { fontSize: ms(26), fontWeight: "bold", color: "#333", marginBottom: vs(14) },
  ratingContainer: { marginBottom: vs(18), alignItems: "center" },
  starsContainer: { flexDirection: "row", alignItems: "center", justifyContent: "center" },
  star: { fontSize: ms(19), color: "#FFD700", marginRight: s(3) },
  halfStar: { fontSize: ms(19), color: "#FFD700", marginRight: s(3) },
  emptyStar: { fontSize: ms(19), color: "#CCCCCC", marginRight: s(3) },
  ratingText: { fontSize: ms(15), fontWeight: "bold", color: "#333", marginLeft: s(8) },
  detailsContainer: {
    width: "100%",
    backgroundColor: "white",
    borderRadius: s(10),
    padding: s(18),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: vs(18),
  },
  detailLabel: { fontSize: ms(15), fontWeight: "bold", color: "#555", marginTop: vs(10) },
  detailValue: { fontSize: ms(15), color: "#333", marginBottom: vs(4), lineHeight: ms(22) },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: vs(18),
  },
  contactButton: {
    backgroundColor: "#007bff",
    paddingVertical: vs(12),
    paddingHorizontal: s(16),
    borderRadius: s(8),
    flex: 1,
    marginRight: s(10),
  },
  reservarButton: {
    backgroundColor: "#28a745",
    paddingVertical: vs(12),
    paddingHorizontal: s(16),
    borderRadius: s(8),
    flex: 1,
    marginLeft: s(10),
  },
  buttonText: { color: "white", fontSize: ms(15), fontWeight: "bold", textAlign: "center" },
});
